<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../favicon.ico">
    
    <title>Administrator - Bridge Apullum</title>
    <link rel="stylesheet" href="css/normalize.css" type="text/css" />
    <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="css/bootstrap-theme.min.css" type="text/css" />
    <link rel="stylesheet" href="css/custom.css" type="text/css" />
    
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
</head>
<body>

    <table style="width: 100%;">
        <tr>
            <td class="bg-green"><img src="images/brg_01.png" width="332" height="150" /></td>
            <td class="bg-green" style="text-align: center"><img src="images/brg_02.png"  width="668" height="100" /></td>
        </tr>
        <tr>
            <td class="bg-white" style="width: 50px;" valign="top">
                <div class="left-menu">
                    <?php if ($user->get_session()) : ?>
                        <div style="padding: 50px 0; margin: 0;">
                            <ul>
                                <li><a href="index.php"><i class="glyphicon glyphicon-arrow-up"></i> Administrator</a></li>
                                <li><a href="../evenimente.php" target="_blank"><i class="glyphicon glyphicon-arrow-down"></i> Website</a></li>
                                <li><hr /></li>
                                <li><a href="send-mail.php?year=2013"><i class="glyphicon glyphicon-list-alt"></i> Trimite Mail <br /> Participanti 2013</a></li>
                                <li><a href="participanti.php?year=2013"><i class="glyphicon glyphicon-user"></i> Participanti <br /> Cupa Unirii 2013</a></li>
                                <li><hr /></li>
                                <li><a href="users.php"><i class="glyphicon glyphicon-align-center"></i> Utilizatori</a></li>
                                <li><a href="my-user.php"><i class="glyphicon glyphicon-chevron-down"></i> Contul Meu</a></li>
                                <li><a href="logout.php"><i class="glyphicon glyphicon-ban-circle"></i> Delogare</a></li>
                            </ul>                    
                        </div>
                    <?php endif ?>
                </div>
            </td>
            <td valign="top" style=" min-height: 998px;">
                <div class="top-menu bg-green-gradient">
                    <?php if (!$user->get_session()) : ?>
                        <a href="login.php" class="btn btn-danger"><i class="glyphicon glyphicon-hand-up"></i> Logare</a>
                        <a href="registration.php" class="btn btn-danger"><i class="glyphicon glyphicon-hand-right"></i> Inregistrare</a>
                    <?php endif ?>
                    <?php if ($user->get_session()) : ?>
                        <table class="pull-right">
                            <tr> 
                                <td>
                                    <a href="logout.php" class="btn btn-danger" style="margin-right: 15px;"><i class="glyphicon glyphicon-ban-circle"></i> Delogare</a>    
                                </td>
                                <td>
                                    <b>Utilizator: </b>
                                    <em><?= $user->getUsername() ?></em>
                                    <br />
                                    <b>Nume: </b>
                                    <em><?= $user->getName() ?></em>
                                </td>
                            </tr>
                        </table>
                    <?php endif ?>
                </div>
                <div class="page-header" style="text-align: center;">
                  <h1>Administrator <small>bridge club apullum</small></h1>
                </div>
            
